name: run

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'GitHub Repo'
        required: true
        default: "metersphere/metersphere"

jobs:
  package-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup java 18
        uses: actions/setup-java@v3
        with:
          java-version: 18
          distribution: 'temurin'
      - name: build
        run: mvn package
      - name: java run
        run: cd target && java -jar pr-comment-summary-1.0-SNAPSHOT.jar ${{ github.event.inputs.repo }}